### ISSUE TITLE
Issue: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by FilipPyrek** [Erasmus2016/backend#13]
It occurs during the game in backend server's console. The room which caused it, seems to be frozen... But other players can connect to the server, create new rooms and play.

Same server:
Error from first room:
```
(node:15802) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): unknown error
(node:15802) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Error from second room:
```
(node:15802) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): unknown error
```

Maybe it's caused by the database stuff... (I have config which @MarioIM sent me)

**Comment by theRealBaccata** [comment]
Does this issue arise if you request a question while playing? What event you exactly requesting from the backend?

**Comment by FilipPyrek** [comment]
Player A receives `roll-the-dice`
Player A send `roll-the-dice`
Player A receives `dice-result` but Player B doesn't receive anything. 
Server doesn't send any events to this particular room anymore.

But seems to be occurring "randomly". Sometimes you throw one or two times and it occurs, sometimes you throw fifteen or twenty times and it occurs...

**Comment by theRealBaccata** [comment]
Thanks for this information, we'll look into it asap.

**Comment by theRealBaccata** [comment]
@FilipPyrek:

Would you please repeat your endeavors, I changed something at the backend. Please have a look at https://github.com/Erasmus2016/backend/commit/dd5f5b557fce18c6562f235f8f97d481fd2cb881

**Comment by FilipPyrek** [comment]
@theRealBaccata 
I have pulled latest commit (2d64f9b75b60f0995566e6f9ce6d76c463c222ab) and it still throws same error => not fixed.

**Comment by theRealBaccata** [comment]
Could you please provide us the latest version of your frontend? We're trying to reproduce your issue.

**Comment by FilipPyrek** [comment]
Just pull https://github.com/Erasmus2016/frontend/tree/v2

**Comment by FilipPyrek** [comment]
Have you tried to put into `config/db.json` wrong credentials?

**Comment by marioreggiori** [comment]
Please try again I think we fixed it.

**Comment by FilipPyrek** [comment]
@MarioIM Yeah, it doesn't log any error anymore, but sometimes the game gets stuck and after several seconds it continues... and nobody receives any question. (I have checked it in chrome dev tools in web sockets frames)

**Comment by theRealBaccata** [comment]
Fixed
