### ISSUE TITLE
Set ACAO header (CORS) to wildcard to allow all domains

### ISSUE THREAD

**Issue by FilipPyrek** [Erasmus2016/backend#3]
We need you to set ACAO header ([CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)) to wildcard to allow all domains, because otherwise we get this error.

![](http://i.imgur.com/daSPv7E.jpg)

You can use https://www.npmjs.com/package/cors middleware for express.js

**Comment by theRealBaccata** [comment]
Hey Filip,

we are working on this issue. Stay tuned.

@MarioIM See commit 1c9dbf62fde96e32e1bd1e0be777a9326e5c68ee

**Comment by FilipPyrek** [comment]
@theRealBaccata why didn't you use the middleware? It's quite common to use many libraries in project in javascript (nodejs in particular) world. It "hides" (obvious) logic of some task which just needs to be done. You don't need to see how is it done, you need to see that "it's there". Right?

unnecessarily too verbose
```javascript
 // Allow CORS.
 app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
 });
```

vs.

obvious, straightforward
```javascript
const cors = require('cors');
app.use(cors());
```

**Comment by theRealBaccata** [comment]
Well this will require another dependency. I try to avoid this.

CORS is now working.
