### ISSUE TITLE
Why do you use global variables? 

### ISSUE THREAD

**Issue by FilipPyrek** [Erasmus2016/backend#4]
Why do you use global variables? 
[https://www.quora.com/Why-are-global-variables-bad](https://www.quora.com/Why-are-global-variables-bad)

Have you ever heart about functional programming? Pure functions etc.? It's huge topic especially in Javascript world (since release of React.js) Everybody does functional today :D
[https://www.youtube.com/playlist?list=PL0zVEGEvSaeEd9hlmCXrk5yUyqUag-n84](https://www.youtube.com/playlist?list=PL0zVEGEvSaeEd9hlmCXrk5yUyqUag-n84)

Or you might know at least dependency injection...

**Comment by theRealBaccata** [comment]
For testing purpose global variables are a good choice.

We can refactor this later-on. There are bigger issues available right now.

**Comment by FilipPyrek** [comment]
https://github.com/ryanmcdermott/clean-code-javascript
