### ISSUE TITLE
Issue: Login event

### ISSUE THREAD

**Issue by FilipPyrek** [Erasmus2016/backend#7]
When I connect two clients to the server, only the one which was connected first gets the *login* event.

I've discovered that when i replace 

[class/controller.js line 66](https://github.com/Erasmus2016/backend/blob/master/class/controller.js#L66)
```javascript
this.room.emit('login');
```

with 
```javascript
setTimeout(() => this.room.emit('login'), 1000);
```
it works. (booth clients get *login* event)

**Comment by marioreggiori** [comment]
could you send a "hello" event after the "connect" event?
it seems that the connection isn't completely established at this time
i can't find any logical mistake on my side...

**Comment by FilipPyrek** [comment]
Maybe if you solve #10, this problem will vanish.

**Comment by theRealBaccata** [comment]
See https://github.com/Erasmus2016/backend/commit/5b13cbfc04e63c8296b1b07c808a1ae6a0c21c36

**Comment by FilipPyrek** [comment]
Yeah, that's fine.
