### ISSUE TITLE
Issue: Is disconnected (waiting) user removed from the stack?

### ISSUE THREAD

**Issue by FilipPyrek** [Erasmus2016/backend#8]
How do you handle when one client disconnects before the [*Controller* was created](https://github.com/Erasmus2016/backend/blob/master/app.js#L28)? Is he really removed from the stack of [*clients*](https://github.com/Erasmus2016/backend/blob/master/app.js#L18)?

Because when I kept refreshing the client, console was saying that new and new and new rooms are created even though I was using only one client.

**Comment by marioreggiori** [comment]
this part isn't finished yet

**Comment by FilipPyrek** [comment]
IMHO this is one of the really basic (and easy to do) parts.
In current conditions it's really hard to develop anything on frontend... please fix it ASAP, thanks.

**Comment by marioreggiori** [comment]
this should be working now
i remove disconnected clients from the queue
