### ISSUE TITLE
Idea: Sending "reason" event before disconnecting the client from the server side.

### ISSUE THREAD

**Issue by FilipPyrek** [Erasmus2016/backend#9]
I see, that server sends the *disconnect* event, but there is no "reason field" to enable us to display to user what happened and not just "ERROR" and then refresh the page.

**Comment by marioreggiori** [comment]
we are working on the reconnect when a player lost connection f.e. (with timeout) but we want to have a playable game first

**Comment by FilipPyrek** [comment]
Reconnecting etc. is not really necessary... you should first focus on basic things like #8 and stuff.
These would be just small events emitted before *disconnect*.

**Comment by marioreggiori** [comment]
we don't disconnect anything... it's the client
i guess it's impossible to send an event to a disconnected client

**Comment by FilipPyrek** [comment]
https://github.com/Erasmus2016/backend/blob/master/class/controller.js#L62

**Comment by marioreggiori** [comment]
https://github.com/Erasmus2016/backend/pull/6/files/e700c16be73d9b88f85aa32b30959200c2f71c4a#r96146928

**Comment by FilipPyrek** [comment]
What do you mean by that?

**Comment by FilipPyrek** [comment]
My bad, I didn't read you message well...

> i guess it's impossible to send an event to a disconnected client

who was talking about sending an event to a disconnected client?

**Comment by FilipPyrek** [comment]
If I understand it well, if one player [disconnects](https://github.com/Erasmus2016/backend/blob/master/class/controller.js#L60), the server [sends *disconnect* event](https://github.com/Erasmus2016/backend/blob/master/class/controller.js#L62) to all remaining users in the room, right?

**Comment by marioreggiori** [comment]
no this one is triggering the event emitter (Controller extends EventEmitter)
we want to handle the disconnect inside app.js

**Comment by FilipPyrek** [comment]
Ohh, my bad, ok.
